name: Blog CI/CD

on:
  push:
    barches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 切代码到 runner
      - uses: actions/checkout@v1
      - name: use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present
        
      - name: deploy to server
        run: ssh root@101.42.14.192

    
